version: "3.9"

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1


volumes:
  mysql:

